/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2012, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

/* This file was autogenerated from D:\git\xDrivenDevelopers\sublime-language-1c-bsl\1c.tmLanguage (uuid: ) */
/****************************************************************************************
 * IT MIGHT NOT BE PERFECT ...But it's a good start from an existing *.tmlanguage file. *
 * fileTypes                                                                            *
 ****************************************************************************************/

define(function(require, exports, module) {
"use strict";

var oop = require("../lib/oop");
var TextHighlightRules = require("./text_highlight_rules").TextHighlightRules;

var BSLHighlightRules = function() {
    // regexp must not have capturing parentheses. Use (?:) instead.
    // regexps are ordered -> the first match is used

        var identifier = "[$A-Za-z_\\x7f-\\uffff][$\\w\\x7f-\\uffff]*";

        var keywords = (
            "Прервать|Break|Продолжить|Continue|Возврат|Return|" +
            "Если|If|Иначе|Else|ИначеЕсли|ElsIf|Тогда|Then|КонецЕсли|EndIf|" +
            "Попытка|Try|Исключение|Except|КонецПопытки|EndTry|ВызватьИсключение|Raise|" +
            "or|on|unless|until|and|yes"
        );

        var langConstant = (
            "Неопределено|Undefined|Истина|True|Ложь|False|NULL"
        );

        var supportClass = (
            "Array|Boolean|Date|Function|Number|Object|RegExp|ReferenceError|String|" +
            "Error|EvalError|InternalError|RangeError|ReferenceError|StopIteration|" +
            "SyntaxError|TypeError|URIError|"  +
            "ArrayBuffer|Float32Array|Float64Array|Int16Array|Int32Array|Int8Array|" +
            "Uint16Array|Uint32Array|Uint8Array|Uint8ClampedArray"
        );

        var supportFunction = (
            "СтрДлина|StrLen|СокрЛ|TrimL|СокрП|TrimR|СокрЛП|TrimAll|Лев|Left|Прав|" +
            "Right|Сред|Mid|СтрНайти|StrFind|ВРег|Upper|НРег|Lower|" +
            "ТРег|Title|Символ|Char|КодСимвола|CharCode|ПустаяСтрока|" +
            "IsBlankString|СтрЗаменить|StrReplace|СтрЧислоСтрок|StrLineCount|" +
            "СтрПолучитьСтроку|StrGetLine|СтрЧислоВхождений|StrOccurrenceCount|" +
            "СтрСравнить|StrCompare|СтрНачинаетсяС|StrStartWith|СтрЗаканчиваетсяНа|" +
            "StrEndsWith|СтрРазделить|StrSplit|СтрСоединить|StrConcat|" +
            "ПоказатьВопрос|ShowQueryBox|Вопрос|DoQueryBox|ПоказатьПредупреждение|ShowMessageBox|Предупреждение|DoMessageBox|Сообщить|Message|ОчиститьСообщения|ClearMessages|ОповеститьОбИзменении|NotifyChanged|Состояние|Status|Сигнал|Beep|ПоказатьЗначение|ShowValue|ОткрытьЗначение|OpenValue|Оповестить|Notify|ОбработкаПрерыванияПользователя|UserInterruptProcessing|ОткрытьСодержаниеСправки|OpenHelpContent|ОткрытьИндексСправки|OpenHelpIndex|ОткрытьСправку|OpenHelp|ПоказатьИнформациюОбОшибке|ShowErrorInfo|КраткоеПредставлениеОшибки|BriefErrorDescription|ПодробноеПредставлениеОшибки|DetailErrorDescription|ПолучитьФорму|GetForm|ЗакрытьСправку|CloseHelp|ПоказатьОповещениеПользователя|ShowUserNotification|ОткрытьФорму|OpenForm|ОткрытьФормуМодально|OpenFormModal|АктивноеОкно|ActiveWindow|ВыполнитьОбработкуОповещения|ExecuteNotifyProcessing|"
        );

        var variableLanguage = (
            "ГлавныйИнтерфейс|MainInterface|ГлавныйСтиль|MainStyle|ПараметрЗапуска|LaunchParameter|РабочаяДата|WorkingDate|ХранилищеВариантовОтчетов|ReportsVariantsStorage|ХранилищеНастроекДанныхФорм|FormDataSettingsStorage|ХранилищеОбщихНастроек|CommonSettingsStorage|ХранилищеПользовательскихНастроекДинамическихСписков|DynamicListsUserSettingsStorage|ХранилищеПользовательскихНастроекОтчетов|ReportsUserSettingsStorage|ХранилищеСистемныхНастроек|SystemSettingsStorage"
        );

        var keywordMapper = this.createKeywordMapper({
            "keyword": keywords,
            "constant.language": langConstant,
            // "invalid.illegal": illegal,
            "language.support.class": supportClass,
            "language.support.function": supportFunction,
            "variable.language": variableLanguage
        }, "identifier");
    
    
    this.$rules = {
        start: [{
            include: "#basic"
        }, {
            token: [
                "storage.type.bsl",
                "text",
                "entity.name.function.bsl",
                "text"
            ],
            regex: /\b(Процедура|Procedure|Функция|Function)(\s+)([a-zа-яё0-9_]+)(\s*\()/,
            caseInsensitive: true,
            push: [{
                token: ["text", "storage.modifier.bsl"],
                regex: /(\)\s*)((?:(?:Экспорт|Export)\b)?)/,
                caseInsensitive: true,
                next: "pop"
            }, {
                include: "#basic"
            }, {
                token: "keyword.operator.assignment.bsl",
                regex: /=/
            }, {
                token: "storage.modifier.bsl",
                regex: /\b(?:Знач|Val)\b/,
                caseInsensitive: true
            }, {
                token: "variable.parameter.bsl",
                regex: /[a-zа-яё0-9_]+/,
                caseInsensitive: true
            }],
            comment: "Proc and function definition"
        }, {
            token: [
                "storage.type.var.bsl",
                "text",
                "variable.bsl",
                "text"
            ],
            regex: /\b(Перем|Var)(\s+)([a-zа-яё0-9_]+)(\s*)/,
            caseInsensitive: true,
            push: [{
                token: "storage.modifier.bsl",
                regex: /(?:Экспорт|Export)?/,
                caseInsensitive: true,
                next: "pop"
            }],
            comment: "Define of variable"
        }, {
            token: "storage.type.bsl",
            regex: /\b(?:КонецПроцедуры|EndProcedure|КонецФункции|EndFunction)\b/,
            caseInsensitive: true
        }, {
            token: "keyword.control.import.bsl",
            regex: /#(?:Использовать|Use)\b/,
            caseInsensitive: true
        }, {
            token: keywordMapper,
            regex: identifier
        }, {
            token: "keyword.control.repeat.bsl",
            regex: /\b(?:Пока|While|(?:Для|For)(?:\s+(?:Каждого|Each))?|Из|In|По|To|Цикл|Do|КонецЦикла|EndDo)\b/,
            caseInsensitive: true
        }, {
            token: "keyword.operator.logical.bsl",
            regex: /\b(?:НЕ|NOT|И|AND|ИЛИ|OR)\b/,
            caseInsensitive: true
        }, {
            token: "keyword.operator.comparison.bsl",
            regex: /<=|>=|=|<|>/
        }, {
            token: "keyword.operator.arithmetic.bsl",
            regex: /\+|-|\*|\/|%/
        }, {
            token: "keyword.operator.bsl",
            regex: /;|\?/
        }, {
            token: "support.function.bsl",
            regex: /\b(?:Новый|New)\b/,
            caseInsensitive: true,
            comment: "Functions w/o brackets"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:Цел|Int|Окр|Round|ACos|ACos|ASin|ASin|ATan|ATan|Cos|Cos|Exp|Exp|Log|Log|Log10|Log10|Pow|Pow|Sin|Sin|Sqrt|Sqrt|Tan|Tan)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - функции работы со значениями типа Число"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:Год|Year|Месяц|Month|День|Day|Час|Hour|Минута|Minute|Секунда|Second|НачалоГода|BegOfYear|НачалоДня|BegOfDay|НачалоКвартала|BegOfQuarter|НачалоМесяца|BegOfMonth|НачалоМинуты|BegOfMinute|НачалоНедели|BegOfWeek|НачалоЧаса|BegOfHour|КонецГода|EndOfYear|КонецДня|EndOfDay|КонецКвартала|EndOfQuarter|КонецМесяца|EndOfMonth|КонецМинуты|EndOfMinute|КонецНедели|EndOfWeek|КонецЧаса|EndOfHour|НеделяГода|WeekOfYear|ДеньГода|DayOfYear|ДеньНедели|WeekDay|ТекущаяДата|CurrentDate|ДобавитьМесяц|AddMonth)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - функции работы со значениями типа Дата"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:Тип|Type|ТипЗнч|TypeOf)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - функции работы со значениями типа Тип"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:Булево|Boolean|Число|Number|Строка|String|Дата|Date)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - функции преобразования значений"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:ПоказатьВводЗначения|ShowInputValue|ВвестиЗначение|InputValue|ПоказатьВводЧисла|ShowInputNumber|ВвестиЧисло|InputNumber|ПоказатьВводСтроки|ShowInputString|ВвестиСтроку|InputString|ПоказатьВводДаты|ShowInputDate|ВвестиДату|InputDate)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - функции для вызова диалога ввода данных"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:Формат|Format|ЧислоПрописью|NumberInWords|НСтр|NStr|ПредставлениеПериода|PeriodPresentation|СтрШаблон|StrTemplate)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - функции форматирования"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:ПолучитьОбщийМакет|GetCommonTemplate|ПолучитьОбщуюФорму|GetCommonForm|ПредопределенноеЗначение|PredefinedValue|ПолучитьПолноеИмяПредопределенногоЗначения|GetPredefinedValueFullName)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - функции обращения к конфигурации"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:ПолучитьЗаголовокСистемы|GetCaption|ПолучитьСкоростьКлиентскогоСоединения|GetClientConnectionSpeed|ПодключитьОбработчикОжидания|AttachIdleHandler|УстановитьЗаголовокСистемы|SetCaption|ОтключитьОбработчикОжидания|DetachIdleHandler|ИмяКомпьютера|ComputerName|ЗавершитьРаботуСистемы|Exit|ИмяПользователя|UserName|ПрекратитьРаботуСистемы|Terminate|ПолноеИмяПользователя|UserFullName|ЗаблокироватьРаботуПользователя|LockApplication|КаталогПрограммы|BinDir|КаталогВременныхФайлов|TempFilesDir|ПравоДоступа|AccessRight|РольДоступна|IsInRole|ТекущийЯзык|CurrentLanguage|ТекущийКодЛокализации|CurrentLocaleCode|СтрокаСоединенияИнформационнойБазы|InfoBaseConnectionString|ПодключитьОбработчикОповещения|AttachNotificationHandler|ОтключитьОбработчикОповещения|DetachNotificationHandler|ПолучитьСообщенияПользователю|GetUserMessages|ПараметрыДоступа|AccessParameters|ПредставлениеПриложения|ApplicationPresentation|ТекущийЯзыкСистемы|CurrentSystemLanguage|ЗапуститьСистему|RunSystem|ТекущийРежимЗапуска|CurrentRunMode|УстановитьЧасовойПоясСеанса|SetSessionTimeZone|ЧасовойПоясСеанса|SessionTimeZone|ТекущаяДатаСеанса|CurrentSessionDate|УстановитьКраткийЗаголовокПриложения|SetShortApplicationCaption|ПолучитьКраткийЗаголовокПриложения|GetShortApplicationCaption|ПредставлениеПрава|RightPresentation|ВыполнитьПроверкуПравДоступа|VerifyAccessRights|РабочийКаталогДанныхПользователя|UserDataWorkDir|КаталогДокументов|DocumentsDir|ПолучитьИнформациюЭкрановКлиента|GetClientDisplaysInformation|ТекущийВариантОсновногоШрифтаКлиентскогоПриложения|ClientApplicationBaseFontCurrentVariant|ТекущийВариантИнтерфейсаКлиентскогоПриложения|ClientApplicationInterfaceCurrentVariant|УстановитьЗаголовокКлиентскогоПриложения|SetClientApplicationCaption|ПолучитьЗаголовокКлиентскогоПриложения|GetClientApplicationCaption|НачатьПолучениеКаталогаВременныхФайлов|BeginGettingTempFilesDir|НачатьПолучениеКаталогаДокументов|BeginGettingDocumentsDir|НачатьПолучениеРабочегоКаталогаДанныхПользователя|BeginGettingUserDataWorkDir|ПодключитьОбработчикЗапросаНастроекКлиентаЛицензирования|AttachLicensingClientParametersRequestHandler|ОтключитьОбработчикЗапросаНастроекКлиентаЛицензирования|DetachLicensingClientParametersRequestHandler)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - процедуры и функции сеанса работы"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:ЗначениеВСтрокуВнутр|ValueToStringInternal|ЗначениеИзСтрокиВнутр|ValueFromStringInternal|ЗначениеВФайл|ValueToFile|ЗначениеИзФайла|ValueFromFile)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - процедуры и функции сохранения значений"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:КомандаСистемы|System|ЗапуститьПриложение|RunApp|ПолучитьCOMОбъект|GetCOMObject|ПользователиОС|OSUsers|НачатьЗапускПриложения|BeginRunningApplication)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с операционной системой"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:ПодключитьВнешнююКомпоненту|AttachAddIn|НачатьУстановкуВнешнейКомпоненты|BeginInstallAddIn|УстановитьВнешнююКомпоненту|InstallAddIn|НачатьПодключениеВнешнейКомпоненты|BeginAttachingAddIn)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с внешними компонентами"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:КопироватьФайл|FileCopy|ПереместитьФайл|MoveFile|УдалитьФайлы|DeleteFiles|НайтиФайлы|FindFiles|СоздатьКаталог|CreateDirectory|ПолучитьИмяВременногоФайла|GetTempFileName|РазделитьФайл|SplitFile|ОбъединитьФайлы|MergeFiles|ПолучитьФайл|GetFile|НачатьПомещениеФайла|BeginPutFile|ПоместитьФайл|PutFile|ЭтоАдресВременногоХранилища|IsTempStorageURL|УдалитьИзВременногоХранилища|DeleteFromTempStorage|ПолучитьИзВременногоХранилища|GetFromTempStorage|ПоместитьВоВременноеХранилище|PutToTempStorage|ПодключитьРасширениеРаботыСФайлами|AttachFileSystemExtension|НачатьУстановкуРасширенияРаботыСФайлами|BeginInstallFileSystemExtension|УстановитьРасширениеРаботыСФайлами|InstallFileSystemExtension|ПолучитьФайлы|GetFiles|ПоместитьФайлы|PutFiles|ЗапроситьРазрешениеПользователя|RequestUserPermission|ПолучитьМаскуВсеФайлы|GetAllFilesMask|ПолучитьМаскуВсеФайлыКлиента|GetClientAllFilesMask|ПолучитьМаскуВсеФайлыСервера|GetServerAllFilesMask|ПолучитьРазделительПути|GetPathSeparator|ПолучитьРазделительПутиКлиента|GetClientPathSeparator|ПолучитьРазделительПутиСервера|GetServerPathSeparator|НачатьПодключениеРасширенияРаботыСФайлами|BeginAttachingFileSystemExtension|НачатьЗапросРазрешенияПользователя|BeginRequestingUserPermission|НачатьПоискФайлов|BeginFindingFiles|НачатьСозданиеКаталога|BeginCreatingDirectory|НачатьКопированиеФайла|BeginCopyingFile|НачатьПеремещениеФайла|BeginMovingFile|НачатьУдалениеФайлов|BeginDeletingFiles|НачатьПолучениеФайлов|BeginGettingFiles|НачатьПомещениеФайлов|BeginPuttingFiles)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с файлами"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:НачатьТранзакцию|BeginTransaction|ЗафиксироватьТранзакцию|CommitTransaction|ОтменитьТранзакцию|RollbackTransaction|УстановитьМонопольныйРежим|SetExclusiveMode|МонопольныйРежим|ExclusiveMode|ПолучитьОперативнуюОтметкуВремени|GetRealTimeTimestamp|ПолучитьСоединенияИнформационнойБазы|GetInfoBaseConnections|НомерСоединенияИнформационнойБазы|InfoBaseConnectionNumber|КонфигурацияИзменена|ConfigurationChanged|КонфигурацияБазыДанныхИзмененаДинамически|DataBaseConfigurationChangedDynamically|УстановитьВремяОжиданияБлокировкиДанных|SetLockWaitTime|ОбновитьНумерациюОбъектов|RefreshObjectsNumbering|ПолучитьВремяОжиданияБлокировкиДанных|GetLockWaitTime|КодЛокализацииИнформационнойБазы|InfoBaseLocaleCode|УстановитьМинимальнуюДлинуПаролейПользователей|SetUserPasswordMinLength|ПолучитьМинимальнуюДлинуПаролейПользователей|GetUserPasswordMinLength|ИнициализироватьПредопределенныеДанные|InitializePredefinedData|УдалитьДанныеИнформационнойБазы|EraseInfoBaseData|УстановитьПроверкуСложностиПаролейПользователей|SetUserPasswordStrengthCheck|ПолучитьПроверкуСложностиПаролейПользователей|GetUserPasswordStrengthCheck|ПолучитьСтруктуруХраненияБазыДанных|GetDBStorageStructureInfo|УстановитьПривилегированныйРежим|SetPrivilegedMode|ПривилегированныйРежим|PrivilegedMode|ТранзакцияАктивна|TransactionActive|НеобходимостьЗавершенияСоединения|ConnectionStopRequest|НомерСеансаИнформационнойБазы|InfoBaseSessionNumber|ПолучитьСеансыИнформационнойБазы|GetInfoBaseSessions|ЗаблокироватьДанныеДляРедактирования|LockDataForEdit|УстановитьСоединениеСВнешнимИсточникомДанных|ConnectExternalDataSource|РазблокироватьДанныеДляРедактирования|UnlockDataForEdit|РазорватьСоединениеСВнешнимИсточникомДанных|DisconnectExternalDataSource|ПолучитьБлокировкуСеансов|GetSessionsLock|УстановитьБлокировкуСеансов|SetSessionsLock|ОбновитьПовторноИспользуемыеЗначения|RefreshReusableValues|УстановитьБезопасныйРежим|SetSafeMode|БезопасныйРежим|SafeMode|ПолучитьДанныеВыбора|GetChoiceData|УстановитьЧасовойПоясИнформационнойБазы|SetInfoBaseTimeZone|ПолучитьЧасовойПоясИнформационнойБазы|GetInfoBaseTimeZone|ПолучитьОбновлениеКонфигурацииБазыДанных|GetDataBaseConfigurationUpdate|УстановитьБезопасныйРежимРазделенияДанных|SetDataSeparationSafeMode|БезопасныйРежимРазделенияДанных|DataSeparationSafeMode|УстановитьВремяЗасыпанияПассивногоСеанса|SetPassiveSessionHibernateTime|ПолучитьВремяЗасыпанияПассивногоСеанса|GetPassiveSessionHibernateTime|УстановитьВремяЗавершенияСпящегоСеанса|SetHibernateSessionTerminateTime|ПолучитьВремяЗавершенияСпящегоСеанса|GetHibernateSessionTerminateTime|ПолучитьТекущийСеансИнформационнойБазы|GetCurrentInfoBaseSession|ПолучитьИдентификаторКонфигурации|GetConfigurationID|УстановитьНастройкиКлиентаЛицензирования|SetLicensingClientParameters|ПолучитьИмяКлиентаЛицензирования|GetLicensingClientName|ПолучитьДополнительныйПараметрКлиентаЛицензирования|GetLicensingClientAdditionalParameter)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с информационной базой"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:НайтиПомеченныеНаУдаление|FindMarkedForDeletion|НайтиПоСсылкам|FindByRef|УдалитьОбъекты|DeleteObjects|УстановитьОбновлениеПредопределенныхДанныхИнформационнойБазы|SetInfoBasePredefinedDataUpdate|ПолучитьОбновлениеПредопределенныхДанныхИнформационнойБазы|GetInfoBasePredefinedData)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с данными информационной базы"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:XMLСтрока|XMLString|XMLЗначение|XMLValue|XMLТип|XMLType|XMLТипЗнч|XMLTypeOf|ИзXMLТипа|FromXMLType|ВозможностьЧтенияXML|CanReadXML|ПолучитьXMLТип|GetXMLType|ПрочитатьXML|ReadXML|ЗаписатьXML|WriteXML|НайтиНедопустимыеСимволыXML|FindDisallowedXMLCharacters|ИмпортМоделиXDTO|ImportXDTOModel|СоздатьФабрикуXDTO|CreateXDTOFactory)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с XML"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:ЗаписатьJSON|WriteJSON|ПрочитатьJSON|ReadJSON|ПрочитатьДатуJSON|ReadJSONDate|ЗаписатьДатуJSON|WriteJSONDate)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с JSON"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:ЗаписьЖурналаРегистрации|WriteLogEvent|ПолучитьИспользованиеЖурналаРегистрации|GetEventLogUsing|УстановитьИспользованиеЖурналаРегистрации|SetEventLogUsing|ПредставлениеСобытияЖурналаРегистрации|EventLogEventPresentation|ВыгрузитьЖурналРегистрации|UnloadEventLog|ПолучитьЗначенияОтбораЖурналаРегистрации|GetEventLogFilterValues|УстановитьИспользованиеСобытияЖурналаРегистрации|SetEventLogEventUse|ПолучитьИспользованиеСобытияЖурналаРегистрации|GetEventLogEventUse|СкопироватьЖурналРегистрации|CopyEventLog|ОчиститьЖурналРегистрации|ClearEventLog)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с журналом регистрации"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:ЗначениеВДанныеФормы|ValueToFormData|ДанныеФормыВЗначение|FormDataToValue|КопироватьДанныеФормы|CopyFormData|УстановитьСоответствиеОбъектаИФормы|SetObjectAndFormConformity|ПолучитьСоответствиеОбъектаИФормы|GetObjectAndFormConformity)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с универсальными объектами"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:ПолучитьФункциональнуюОпцию|GetFunctionalOption|ПолучитьФункциональнуюОпциюИнтерфейса|GetInterfaceFunctionalOption|УстановитьПараметрыФункциональныхОпцийИнтерфейса|SetInterfaceFunctionalOptionParameters|ПолучитьПараметрыФункциональныхОпцийИнтерфейса|GetInterfaceFunctionalOptionParameters|ОбновитьИнтерфейс|RefreshInterface)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с функциональными опциями"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:УстановитьРасширениеРаботыСКриптографией|InstallCryptoExtension|НачатьУстановкуРасширенияРаботыСКриптографией|BeginInstallCryptoExtension|ПодключитьРасширениеРаботыСКриптографией|AttachCryptoExtension|НачатьПодключениеРасширенияРаботыСКриптографией|BeginAttachingCryptoExtension)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы с криптографией"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:УстановитьСоставСтандартногоИнтерфейсаOData|SetStandardODataInterfaceContent|ПолучитьСоставСтандартногоИнтерфейсаOData|GetStandardODataInterfaceContent)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Процедуры и функции работы со стандартным интерфейсом OData"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:Мин|Min|Макс|Max|ОписаниеОшибки|ErrorDescription|Вычислить|Eval|ИнформацияОбОшибке|ErrorInfo|Base64Значение|Base64Value|Base64Строка|Base64String|ЗаполнитьЗначенияСвойств|FillPropertyValues|ЗначениеЗаполнено|ValueIsFilled|ПолучитьПредставленияНавигационныхСсылок|GetURLsPresentations|НайтиОкноПоНавигационнойСсылке|FindWindowByURL|ПолучитьОкна|GetWindows|ПерейтиПоНавигационнойСсылке|GotoURL|ПолучитьНавигационнуюСсылку|GetURL|ПолучитьДопустимыеКодыЛокализации|GetAvailableLocaleCodes|ПолучитьНавигационнуюСсылкуИнформационнойБазы|GetInfoBaseURL|ПредставлениеКодаЛокализации|LocaleCodePresentation|ПолучитьДопустимыеЧасовыеПояса|GetAvailableTimeZones|ПредставлениеЧасовогоПояса|TimeZonePresentation|ТекущаяУниверсальнаяДата|CurrentUniversalDate|ТекущаяУниверсальнаяДатаВМиллисекундах|CurrentUniversalDateInMilliseconds|МестноеВремя|ToLocalTime|УниверсальноеВремя|ToUniversalTime|ЧасовойПояс|TimeZone|СмещениеЛетнегоВремени|DaylightTimeOffset|СмещениеСтандартногоВремени|StandardTimeOffset|КодироватьСтроку|EncodeString|РаскодироватьСтроку|DecodeString|Найти|Find)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Прочие процедуры и функции"
        }, {
            token: "support.function.bsl",
            regex: /\b(?:ПередНачаломРаботыСистемы|BeforeStart|ПриНачалеРаботыСистемы|OnStart|ПередЗавершениемРаботыСистемы|BeforeExit|ПриЗавершенииРаботыСистемы|OnExit|ОбработкаВнешнегоСобытия|ExternEventProcessing|УстановкаПараметровСеанса|SessionParametersSetting|ПриИзмененииПараметровЭкрана|OnChangeDisplaySettings)\s*(?=\()/,
            caseInsensitive: true,
            comment: "Глобальный контекст - События приложения и сеанса"
        }, {
            token: "support.class.bsl",
            regex: /\b(?:WSСсылки|WSReferences|БиблиотекаКартинок|PictureLib|БиблиотекаМакетовОформленияКомпоновкиДанных|DataCompositionAppearanceTemplateLib|БиблиотекаСтилей|StyleLib|БизнесПроцессы|BusinessProcesses|ВнешниеИсточникиДанных|ExternalDataSources|ВнешниеОбработки|ExternalDataProcessors|ВнешниеОтчеты|ExternalReports|Документы|Documents|ДоставляемыеУведомления|DeliverableNotifications|ЖурналыДокументов|DocumentJournals|Задачи|Tasks|ИспользованиеРабочейДаты|WorkingDateUse|ИсторияРаботыПользователя|UserWorkHistory|Константы|Constants|КритерииОтбора|FilterCriteria|Метаданные|Metadata|Обработки|DataProcessors|ОтправкаДоставляемыхУведомлений|DeliverableNotificationSend|Отчеты|Reports|ПараметрыСеанса|SessionParameters|Перечисления|Enums|ПланыВидовРасчета|ChartsOfCalculationTypes|ПланыВидовХарактеристик|ChartsOfCharacteristicTypes|ПланыОбмена|ExchangePlans|ПланыСчетов|ChartsOfAccounts|ПолнотекстовыйПоиск|FullTextSearch|ПользователиИнформационнойБазы|InfoBaseUsers|Последовательности|Sequences|РасширенияКонфигурации|ConfigurationExtensions|РегистрыБухгалтерии|AccountingRegisters|РегистрыНакопления|AccumulationRegisters|РегистрыРасчета|CalculationRegisters|РегистрыСведений|InformationRegisters|РегламентныеЗадания|ScheduledJobs|СериализаторXDTO|XDTOSerializer|Справочники|Catalogs|СредстваГеопозиционирования|LocationTools|СредстваКриптографии|CryptoToolsManager|СредстваМультимедиа|MultimediaTools|СредстваПочты|MailTools|СредстваТелефонии|TelephonyTools|ФабрикаXDTO|XDTOFactory|ФоновыеЗадания|BackgroundJobs|ХранилищаНастроек|SettingsStorages|ВстроенныеПокупки|InAppPurchases|ОтображениеРекламы|AdRepresentationПанельЗадачОС|OSTaskbar|ПроверкаВстроенныхПокупок|InAppPurchasesValidation)(?=[^\wа-яё]|$)/,
            caseInsensitive: true,
            comment: "Глобальный контекст - Свойства (классы)"
        }, {
            token: "storage.modifier.bsl",
            regex: /&(?:НаКлиенте(?:НаСервере(?:БезКонтекста)?)?|AtClient(?:AtServer(?:NoContext)?)?|НаСервере(?:БезКонтекста)?|AtServer(?:NoContext)?)/,
            caseInsensitive: true
        }, {
            token: "keyword.other.preprocessor.bsl",
            regex: /#(?:Если|If|ИначеЕсли|ElsIf|Иначе|Else|КонецЕсли|EndIf).*(?:Тогда|Then)?/,
            caseInsensitive: true
        }, {
            token: [
                "keyword.other.section.bsl",
                "text",
                "entity.name.section.bsl"
            ],
            regex: /(#(?:Область|Region))(?:(\s+)([\wа-яё]+))?/,
            caseInsensitive: true,
            push: [{
                token: "text",
                regex: /$/,
                next: "pop"
            }],
            comment: "Region start"
        }, {
            token: "keyword.other.section.bsl",
            regex: /#(?:КонецОбласти|EndRegion)/,
            caseInsensitive: true,
            comment: "Region end"
        }],
        "#query": [{
            token: "keyword.control.sdbl",
            regex: /\b(?:Выбрать|Select(?:\s+Разрешенные|Allowed)?(?:\s+Различные|Distinct)?(?:\s+Первые|Top)?)\b/,
            caseInsensitive: true,
            push: [{
                token: "text",
                regex: /(?=\"[^\"])/,
                next: "pop"
            }, {
                token: "comment.line.double-slash.bsl",
                regex: /^\s*\/\//,
                push: [{
                    token: "comment.line.double-slash.bsl",
                    regex: /$/,
                    next: "pop"
                }, {
                    defaultToken: "comment.line.double-slash.bsl"
                }]
            }, {
                token: "comment.line.double-slash.sdbl",
                regex: /\/\/(?:\"\"|[^\"])*/
            }, {
                token: "string.quoted.double.sdbl",
                regex: /\"\"[^"]*\"\"/
            }, {
                include: "source.sdbl"
            }]
        }],
        "#basic": [{
            token: "comment.line.double-slash.bsl",
            regex: /\/\//,
            push: [{
                token: "comment.line.double-slash.bsl",
                regex: /$/,
                next: "pop"
            }, {
                defaultToken: "comment.line.double-slash.bsl"
            }]
        }, {
            token: "string.quoted.double.bsl",
            regex: /\"/,
            push: [{
                token: "string.quoted.double.bsl",
                regex: /\"(?![\"])/,
                next: "pop"
            }, {
                include: "#query"
            }, {
                token: "constant.character.escape.bsl",
                regex: /\"\"/
            }, {
                token: "comment.line.double-slash.bsl",
                regex: /^\s*\/\/.*$/
            }, {
                defaultToken: "string.quoted.double.bsl"
            }]
        }, {
            token: "constant.numeric.bsl",
            regex: /\b(?:[\da-fA-F]{8}-(?:[\da-fA-F]{4}-){3}[\da-fA-F]{12}|\d+\.?\d*)\b/
        }, {
            token: "constant.other.date.bsl",
            regex: /\'\d{4}[^\d\']*\d{2}[^\d\']*\d{2}(?:[^\d\']*\d{2}[^\d\']*\d{2}(?:[^\d\']*\d{2})?)?\'/
        }, {
            token: "keyword.operator.bsl",
            regex: /,/
        }]
    }
    
    this.normalizeRules();
};

BSLHighlightRules.metaData = {
    name: "BSL",
    scopeName: "source.bsl",
    fileTypes: ["bsl", "os"]
}


oop.inherits(BSLHighlightRules, TextHighlightRules);

exports.BSLHighlightRules = BSLHighlightRules;
});